#! /bin/sh

bash /home/velocitatem/.config/bspwm/displays.sh

pgrep -x sxhkd > /dev/null || sxhkd &


bash ~/.config/polybar/launch.sh --hack &

wal -l -t -i /mnt/s/Pictures/Wallpapers/LightAcademiaMin/ --saturate 0.8

# set the cursor
xsetroot -cursor_name left_ptr

# set light systmm theme


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# set emacs always tiled and monocle
bspc rule -a Emacs desktop='^4' state=tiled follow=on
